# Generated by Django 4.2.24 on 2025-10-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='precio',
            new_name='precio_venta',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(choices=[('mecanica', 'Mecanica'), ('electrica', 'Electrica'), ('motor', 'Motor'), ('carroceria', 'Carroceria'), ('otros', 'Otros')], default='mecanica', max_length=30),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad maxima planificada'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_seguridad',
            field=models.PositiveIntegerField(default=0, help_text='Nivel minimo recomendado'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='tiempo_reposicion_dias',
            field=models.PositiveIntegerField(default=0, help_text='Dias estimados para reposicion'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicacion fisica, ej: Rack A-01', max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=20),
        ),
    ]
