# Generated by Django 4.2.24 on 2025-10-16 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_remove_repuesto_precio_repuesto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.repuesto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
