# Generated by Django 4.2.24 on 2025-10-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo interno estimado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(help_text='Duracion aproximada en minutos'),
        ),
    ]
