# Generated by Django 4.2.24 on 2025-10-17 03:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelizacion', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL('DROP INDEX IF EXISTS fidelizaci_client_03ab97_idx'),
                migrations.RunSQL('DROP INDEX IF EXISTS historial_cliente_fecha_idx'),
                migrations.RunSQL(
                    'CREATE INDEX IF NOT EXISTS fidelizacio_cliente_ba6a58_idx '
                    'ON fidelizacion_historialpuntos (cliente_id, fecha)'
                ),
                migrations.RunSQL('DROP INDEX IF EXISTS fidelizaci_refere_3acf64_idx'),
                migrations.RunSQL('DROP INDEX IF EXISTS historial_referencia_idx'),
                migrations.RunSQL(
                    'CREATE INDEX IF NOT EXISTS fidelizacio_referen_d11e8f_idx '
                    'ON fidelizacion_historialpuntos (referencia)'
                ),
                migrations.RunSQL('DROP INDEX IF EXISTS fidelizaci_tipo_b1d104_idx'),
                migrations.RunSQL('DROP INDEX IF EXISTS historial_tipo_idx'),
                migrations.RunSQL(
                    'CREATE INDEX IF NOT EXISTS fidelizacio_tipo_093b5d_idx '
                    'ON fidelizacion_historialpuntos (tipo)'
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='historialpuntos',
                    name='historial_cliente_fecha_idx',
                ),
                migrations.AddIndex(
                    model_name='historialpuntos',
                    index=models.Index(
                        fields=['cliente', 'fecha'],
                        name='fidelizacio_cliente_ba6a58_idx',
                    ),
                ),
                migrations.RemoveIndex(
                    model_name='historialpuntos',
                    name='historial_referencia_idx',
                ),
                migrations.AddIndex(
                    model_name='historialpuntos',
                    index=models.Index(
                        fields=['referencia'],
                        name='fidelizacio_referen_d11e8f_idx',
                    ),
                ),
                migrations.RemoveIndex(
                    model_name='historialpuntos',
                    name='historial_tipo_idx',
                ),
                migrations.AddIndex(
                    model_name='historialpuntos',
                    index=models.Index(
                        fields=['tipo'],
                        name='fidelizacio_tipo_093b5d_idx',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='historialpuntos',
            name='monto_pesos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
