# Generated by Django 4.2.24 on 2025-10-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelizacion', '0002_rename_fidelizaci_client_03ab97_idx_fidelizacio_cliente_ba6a58_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configpuntos',
            options={'verbose_name': 'configuración de puntos', 'verbose_name_plural': 'configuraciones de puntos'},
        ),
        migrations.AlterField(
            model_name='configpuntos',
            name='exclusiones_categorias',
            field=models.JSONField(blank=True, default=list, help_text='Lista de categorías (texto) excluidas del programa.'),
        ),
        migrations.AlterField(
            model_name='configpuntos',
            name='niveles_config',
            field=models.JSONField(blank=True, default=dict, help_text="Configuración opcional de niveles {'Bronce': 0, 'Plata': 5000, ...}."),
        ),
        migrations.AlterField(
            model_name='historialpuntos',
            name='tipo',
            field=models.CharField(choices=[('gana', 'Gana puntos'), ('usa', 'Usa puntos'), ('bono', 'Bonificación'), ('ajuste', 'Ajuste manual'), ('reversa', 'Reversión')], max_length=12),
        ),
    ]
