# Generated by Django 4.2.24 on 2025-09-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['placa'],
            },
        ),
    ]
