# Generated by Django 4.2.24 on 2025-10-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_loyalty_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto pagado final.', max_digits=10),
        ),
    ]
