# Generated by Django 4.2.24 on 2025-09-30 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='cliente',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_cita_fecha_i_e30ff3_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_cita_vehicul_3a6bac_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_cita_cliente_a6c6b6_idx',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='notas',
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='titulo',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No asistió')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='vehiculos.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_inicio'], name='citas_cita_fecha_i_533543_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
