# Generated by Django 4.2.24 on 2025-10-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=25, verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono'], name='clientes_cl_telefon_6177bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'),
        ),
    ]
