# Generated by Django 4.2.24 on 2025-10-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_empresa',
            field=models.BooleanField(default=False, verbose_name='Es empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origen',
            field=models.CharField(choices=[('referido', 'Referido'), ('online', 'Canal digital'), ('visita', 'Visita espontánea'), ('corporativo', 'Convenio corporativo'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_contacto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último contacto'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['documento'], name='clientes_cl_documen_76f212_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['origen'], name='clientes_cl_origen_30a5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['es_empresa'], name='clientes_cl_es_empr_8e5a20_idx'),
        ),
    ]
