# Generated by Django 4.2.24 on 2025-10-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_puntos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_cl_puntos__71196f_idx',
            old_name='clientes_clie_puntos_8a2c2d_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='origen',
            field=models.CharField(choices=[('referido', 'Referido'), ('online', 'Canal digital'), ('visita', 'Visita espontanea'), ('corporativo', 'Convenio corporativo'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_contacto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo contacto'),
        ),
    ]
